name: Firs Work-flow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: |
          echo "Hello All !!!!!!!!!!!!"
          echo "Hello Again !!!!!!!!!!"
      - name: Print Bye
        run: echo "Bye !!!!!!!!!"
